### ISSUE TITLE
Is pod for chaincode container mandatory?

### ISSUE THREAD

**Issue by khanhnb** [blockchainvn/hyperledger-fabric-k8s#1]
Hi,

Is creating pod for chaincode container necessary? Because my fabric network on kubernetes works well without chaincode pod except when peer pod is rescheduled on another nodes (chaincode container has to be reinstalled).

Thanks

**Comment by vjtc0n** [comment]
Hi,
Thanks for asking.
We built a pod of a chaincode container for only testing (you know, for logging, debugging, etc.)
About rescheduled nodes, persistent peer will solve your problem.
Cheers.
